#pragma once
#include "InputEvent.h"

class GameEvent : public Event
{
public:
	enum GameEventTypes
	{
		QUIT_GAME = InputEvent::NUM_INPUT_EVENTS,
		LOAD_GAME,
		GO_TO_TITLE_SCREEN,
		GO_TO_OVERWORLD,
		GO_TO_OPTIONS,
		START_GAME,
		CLICK_BUTTON,
		MOVE_MOUSE,
		TOGGLE_UNIT_ANIMATION,
		CHANGE_UNIT_ANIMATION,
		CHANGE_UNIT_ANIMATION_SPEED,
		PAUSE,
		UNPAUSE,
		SUBTRACT_POINTS,
		PLAYER_UP,
		PLAYER_DOWN,
		PLAYER_LEFT,
		PLAYER_RIGHT,
		BEGIN_BATTLE,
		RESTART_BATTLE,
		ENTER_SHOOTING_MODE,
		BEGIN_ENEMY_TURN,
		BEGIN_PLAYER_TURN,
		RELOCATE_BATTLING_UNITS,
		FIRE_GUN,
		PLAYER_DIES,
		PLAYER_RELOADS,
		PLAYER_HEALS,
		LOCK_PLAYER_MOVEMENT,
		UNLOCK_PLAYER_MOVEMENT,
		BEGIN_READ_TEXT,
		READ_TEXT,
		ADD_TO_MESSAGES,
		PLAY_SOUND,
		TOGGLE_SOUND,
		PLAYER_DASH,
		CHANGE_LANGUAGE,
		SHOW_TALKING_ICON,
		HIDE_TALKING_ICON,
		NUM_GAME_EVENTS
	};

	GameEvent(GameEventTypes type);
	~GameEvent();
};